#!/bin/bash
result="["
rm samples.json
for file in samples/*; do 
    set -f
    contents="$(cat "$file" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')";
    f="$(basename $file)"
    result+='{"name":'
    result+="\"$f\"";
    result+=',"code":'
    result+="\"$contents\"";
    result+='},'
done; 
result=${result::-1}
result+="]"
echo "$result" | python3 -m json.tool >> samples.json
